services:
  crud_web_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    container_name: norbitpizza
    depends_on:
      - pizza_db
      - order_db

  pizza_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: norbit_pizzas
    ports:
      - "5432:5432"
    volumes:
      - pizza_data:/var/lib/postgresql/data

  order_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: norbit_orders
    ports:
      - "5433:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

volumes:
  pizza_data:
  order_data: